name: registro_ponto_agro_cana_forte
description: Aplicativo de registro de ponto para Agro Cana Forte

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  qr_code_scanner_plus: ^2.0.12
  camera: ^0.10.6
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  workmanager: ^0.9.0
  intl: ^0.18.1
  # NOVO: para obter informações do aplicativo na tela de perfil
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true